"use client";
import Image from "next/image";
import Link from "next/link";
import {usePathname} from "next/navigation";
import {useEffect,useState} from "react";
import {Languages,LogOut,Menu,SunMoon,X} from "lucide-react";
import type {LucideIcon} from "lucide-react";
import kcsLogo from "@/public/kcs.jpg";

type Item=readonly [string,string,LucideIcon];
export function MobileMenu({items,label="Navigation",onLogout}:{items:readonly Item[];label?:string;onLogout?:()=>void}){const pathname=usePathname();const[open,setOpen]=useState(false);const[pending,setPending]=useState("");const[lang,setLang]=useState<"fr"|"en">("fr");const clean=(pathname.replace(/\/+$/ ,"")||"/");useEffect(()=>{setOpen(false);setPending("")},[pathname]);useEffect(()=>{setLang(document.documentElement.lang==="en"?"en":"fr");const update=(event:Event)=>setLang((event as CustomEvent<string>).detail==="en"?"en":"fr");window.addEventListener("kcs-language-change",update);return()=>window.removeEventListener("kcs-language-change",update)},[]);useEffect(()=>{document.body.classList.toggle("mobile-menu-open",open);return()=>document.body.classList.remove("mobile-menu-open")},[open]);const active=(href:string)=>{const target=href.replace(/\/+$/ ,"")||"/";return target==="/"?clean==="/":clean===target||clean.startsWith(target+"/")};const proxy=(id:string)=>{document.getElementById(id)?.click();setOpen(false)};return <div className="mobile-menu-root"><button className="mobile-menu-toggle" type="button" onClick={()=>setOpen(value=>!value)} aria-expanded={open} aria-controls="kcs-mobile-menu" aria-label={open?"Fermer le menu":"Ouvrir le menu"}>{open?<X/>:<Menu/>}</button>{open&&<button className="mobile-menu-backdrop" onClick={()=>setOpen(false)} aria-label="Fermer le menu"/>}<nav id="kcs-mobile-menu" className={open?"mobile-menu-drawer open":"mobile-menu-drawer"} aria-label={label}><div className="mobile-menu-heading"><span><Image src={kcsLogo} alt="Kinshasa Christian School" width={46} height={46}/></span><div><b>Parent Election</b><small>{"Navigation s\u00e9curis\u00e9e"}</small></div></div><div className="mobile-menu-links">{items.map(([href,text,Icon])=><Link key={href} href={href} onClick={()=>setPending(href)} className={active(href)||pending===href?"active":""} aria-current={active(href)?"page":undefined}><Icon/><span>{text}</span></Link>)}</div><div className="mobile-menu-settings"><button type="button" onClick={()=>proxy("kcs-theme-toggle")}><SunMoon/><span>{"Th\u00e8me"}</span></button><button type="button" onClick={()=>proxy("kcs-language-toggle")}><Languages/><span data-no-translate>{lang==="fr"?"English (EN)":"Français (FR)"}</span></button>{onLogout&&<button type="button" onClick={()=>{setOpen(false);onLogout()}}><LogOut/><span>{"D\u00e9connexion"}</span></button>}</div></nav></div>}