"use client";
import {FormEvent,useState} from "react";
import {AtSign,Eye,EyeOff,GraduationCap,LockKeyhole,ShieldCheck,Users} from "lucide-react";
import {Header} from "@/components/brand";

type Audience="PARENT"|"STUDENT";
export function OrbitVoterLogin({audience}:{audience:Audience}){
 const[error,setError]=useState("");const[loading,setLoading]=useState(false);const[show,setShow]=useState(false);const[identifier,setIdentifier]=useState("");const[password,setPassword]=useState("");
 const student=audience==="STUDENT";
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setLoading(true);setError("");try{
  const base=process.env.NEXT_PUBLIC_SUPABASE_URL;const key=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;if(!base||!key)throw new Error("SERVICE_NOT_CONFIGURED");
  const response=await fetch(`${base}/functions/v1/orbit-election-login`,{method:"POST",headers:{"content-type":"application/json",apikey:key,authorization:`Bearer ${key}`},body:JSON.stringify({identifier:identifier.trim(),password,audience})});const result=await response.json();if(!response.ok||!result.session_token)throw new Error(result.error||"LOGIN_FAILED");
  sessionStorage.setItem("kcs-voter-session",result.session_token);sessionStorage.setItem("kcs-voter-name",result.display_name||"");sessionStorage.setItem("kcs-election-kind",result.election_kind||"");location.assign("/vote/")
 }catch(reason){const message=reason instanceof Error?reason.message:"LOGIN_FAILED";if(message.includes("ELECTION_LOGIN_CLOSED"))setError("Aucun scrutin de cette catégorie n’est ouvert actuellement.");else if(message.includes("VOTER_ALREADY_VOTED"))setError("Votre bulletin a déjà été enregistré pour ce scrutin.");else if(message.includes("VOTER_NOT_ELIGIBLE"))setError("Votre compte Orbit est valide, mais ne figure pas dans l’électorat autorisé.");else if(message.includes("WRONG_ELECTORATE"))setError("Ce compte n’appartient pas à la catégorie d’électeurs choisie.");else setError("Identifiant ou mot de passe Orbit incorrect.");setLoading(false)}}
 return <><Header/><main className="login-page"><div className="login-orb one"/><div className="login-orb two"/><div className="login-shell"><section className="login-story"><small>KCS ORBIT · {student?"STUDENT GOVERNMENT":"PARENT COMMITTEE"}</small><h1>{student?"Choose the students who will serve and lead.":"Your voice. Our community. One secure choice."}</h1><p>{student?"Elect the President, Vice President, class representative and deputy assigned to your electorate.":"Use the same institutional credentials you already use throughout the KCS Orbit ecosystem."}</p><div className="login-values"><span><ShieldCheck/><b>Secret ballot</b></span><span><Users/><b>One identity, one vote</b></span><span><GraduationCap/><b>Orbit verified</b></span></div></section><form onSubmit={submit} className="login-card" autoComplete="on"><div className="login-card-head"><span><ShieldCheck/></span><small>ORBIT IDENTITY</small><h2>{student?"Student government ballot":"Parent election ballot"}</h2><p>Email or access code + your current ecosystem password.</p></div><label>Email or access code<div><AtSign/><input value={identifier} onChange={e=>setIdentifier(e.target.value)} required autoComplete="username" placeholder="email@ourkcs.org or ACC-..."/></div></label><label>Password<div><LockKeyhole/><input type={show?"text":"password"} value={password} onChange={e=>setPassword(e.target.value)} required minLength={8} autoComplete="current-password"/><button className="login-password-toggle" type="button" onClick={()=>setShow(v=>!v)} aria-label={show?"Hide password":"Show password"}>{show?<EyeOff/>:<Eye/>}</button></div></label>{error&&<p className="status-message error" role="alert">{error}</p>}<button className="login-submit" type="submit" disabled={loading}><ShieldCheck/>{loading?"Secure verification…":"Continue with KCS Orbit"}</button><div className="login-privacy"><ShieldCheck/><p><b>Identity and ballot remain separated.</b><span>Nexus verifies eligibility. The anonymous ballot never stores your password or your choices beside your identity.</span></p></div></form></div></main></>
}