from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER
from reportlab.platypus import SimpleDocTemplate,Paragraph,Spacer,Table,TableStyle,PageBreak,KeepTogether
from reportlab.lib.units import mm
from reportlab.pdfgen import canvas
from reportlab.lib.utils import ImageReader
from hashlib import sha256
import io,os,qrcode
OUT='output/pdf/rapport_officiel_resultats_kcs_modele.pdf';LOGO='public/kcs.jpg'
os.makedirs(os.path.dirname(OUT),exist_ok=True)
verification='https://kcsparentelection.kinshasachristianschool.org/results/?report=SPECIMEN'
fingerprint=sha256(b'KCS OFFICIAL RESULT REPORT SPECIMEN - NO REAL VOTES').hexdigest()
qr=qrcode.QRCode(error_correction=qrcode.constants.ERROR_CORRECT_H,box_size=8,border=2);qr.add_data(verification);qr.make(fit=True);qr_img=qr.make_image(fill_color='#071A2E',back_color='white');buf=io.BytesIO();qr_img.save(buf,format='PNG');buf.seek(0)
navy=colors.HexColor('#071A2E');cyan=colors.HexColor('#009FE0');muted=colors.HexColor('#536473');soft=colors.HexColor('#EFF8FC')
class OfficialDocTemplate(SimpleDocTemplate):
 def afterPage(self):pass
def decorate(c,doc):
 c.saveState();w,h=A4;c.setFillColor(navy);c.rect(0,h-34*mm,w,34*mm,fill=1,stroke=0);c.drawImage(LOGO,14*mm,h-29*mm,22*mm,22*mm,mask='auto',preserveAspectRatio=True);c.setFillColor(colors.white);c.setFont('Helvetica-Bold',14);c.drawString(42*mm,h-14*mm,'KINSHASA CHRISTIAN SCHOOL');c.setFont('Helvetica-Bold',9);c.drawString(42*mm,h-22*mm,'OFFICIAL CERTIFIED ELECTION REPORT - SPECIMEN');c.setFillAlpha(.07);c.drawImage(LOGO,55*mm,70*mm,100*mm,100*mm,mask='auto',preserveAspectRatio=True);c.setFillAlpha(.09);c.setFillColor(navy);c.setFont('Helvetica-Bold',34);c.translate(105*mm,145*mm);c.rotate(35);c.drawCentredString(0,0,'SPECIMEN - NOT OFFICIAL');c.rotate(-35);c.translate(-105*mm,-145*mm);c.setFillAlpha(1);c.setStrokeColor(cyan);c.line(14*mm,13*mm,196*mm,13*mm);c.setFillColor(muted);c.setFont('Courier',6.4);c.drawString(14*mm,8.5*mm,'SHA-256 '+fingerprint);c.setFont('Helvetica',7);c.drawRightString(196*mm,8.5*mm,f'Page {doc.page}');c.restoreState()
doc=OfficialDocTemplate(OUT,pagesize=A4,rightMargin=14*mm,leftMargin=14*mm,topMargin=42*mm,bottomMargin=19*mm,title='KCS Official Election Results - Specimen',author='Kinshasa Christian School Election Committee')
styles=getSampleStyleSheet();styles.add(ParagraphStyle(name='TitleKCS',parent=styles['Title'],fontName='Helvetica-Bold',fontSize=19,leading=23,textColor=navy,spaceAfter=4));styles.add(ParagraphStyle(name='CenterSmall',parent=styles['BodyText'],alignment=TA_CENTER,fontSize=7,textColor=muted));styles.add(ParagraphStyle(name='SectionKCS',parent=styles['Heading2'],fontName='Helvetica-Bold',fontSize=12,textColor=navy,spaceBefore=9,spaceAfter=7));styles.add(ParagraphStyle(name='BodyKCS',parent=styles['BodyText'],fontSize=8.5,leading=12,textColor=muted))
story=[Paragraph('KCS Parent Election 2026 - Official Results',styles['TitleKCS']),Paragraph('School year 2026-2027 | Saturday 19 September 2026 | Africa/Kinshasa',styles['BodyKCS']),Spacer(1,5*mm)]
cert=Table([[Paragraph('<b>CERTIFICATION AND INTEGRITY</b><br/><font name="Courier" size="7">Report ID: '+fingerprint[:16].upper()+'<br/>Integrity checks: PASSED<br/>Status: SPECIMEN - NO REAL VOTES</font>',styles['BodyKCS']),ImageReader(buf)]],colWidths=[142*mm,32*mm],rowHeights=[34*mm]);cert.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,-1),soft),('BOX',(0,0),(-1,-1),.5,colors.HexColor('#CFE7F1')),('VALIGN',(0,0),(-1,-1),'MIDDLE'),('LEFTPADDING',(0,0),(0,0),6*mm),('RIGHTPADDING',(1,0),(1,0),2*mm)]));story+=[cert,Spacer(1,6*mm)]
metrics=Table([['ELIGIBLE VOTERS','BALLOTS CAST','TURNOUT','INTEGRITY'],['165','132','80.00%','PASSED']],colWidths=[45.5*mm]*4,rowHeights=[8*mm,13*mm]);metrics.setStyle(TableStyle([('BOX',(0,0),(-1,-1),.5,colors.HexColor('#DCE4EA')),('INNERGRID',(0,0),(-1,-1),.3,colors.HexColor('#DCE4EA')),('BACKGROUND',(0,0),(-1,0),soft),('TEXTCOLOR',(0,0),(-1,0),muted),('TEXTCOLOR',(0,1),(-1,1),navy),('FONT',(0,0),(-1,0),'Helvetica-Bold',7),('FONT',(0,1),(-1,1),'Helvetica-Bold',14),('ALIGN',(0,0),(-1,-1),'CENTER'),('VALIGN',(0,0),(-1,-1),'MIDDLE')]));story+=[metrics,Spacer(1,6*mm)]
contests=[('PRESIDENT',[('1','#1 Candidate Alpha','72','54.55%','ELECTED'),('2','#2 Candidate Beta','40','30.30%',''),('3','#3 Candidate Gamma','20','15.15%','')],['Margin: 32 votes (24.25 pp)','HHI concentration: 0.412','Effective candidates: 2.43']),('SECRETARY',[('1','#4 Candidate Delta','65','49.24%','ELECTED'),('2','#5 Candidate Epsilon','45','34.09%',''),('3','#6 Candidate Zeta','22','16.67%','')],['Margin: 20 votes (15.15 pp)','HHI concentration: 0.386','Effective candidates: 2.59']),('TREASURER',[('1','#7 Candidate Eta','58','43.94%','ELECTED'),('2','#8 Candidate Theta','52','39.39%',''),('3','#9 Candidate Iota','22','16.67%','')],['Margin: 6 votes (4.55 pp)','HHI concentration: 0.376','Effective candidates: 2.66'])]
for title,rows,notes in contests:
 data=[[title,'','','',''],['RANK','CANDIDATE','VOTES','SHARE','OUTCOME']]+[list(r) for r in rows]+[[notes[0],notes[1],notes[2],'','']]
 t=Table(data,colWidths=[15*mm,88*mm,22*mm,25*mm,32*mm],rowHeights=[9*mm,7*mm]+[8*mm]*len(rows)+[9*mm]);t.setStyle(TableStyle([('SPAN',(0,0),(-1,0)),('BACKGROUND',(0,0),(-1,0),navy),('TEXTCOLOR',(0,0),(-1,0),colors.white),('FONT',(0,0),(-1,0),'Helvetica-Bold',10),('BACKGROUND',(0,1),(-1,1),soft),('FONT',(0,1),(-1,1),'Helvetica-Bold',7),('TEXTCOLOR',(0,1),(-1,1),muted),('FONT',(0,2),(-1,-2),'Helvetica',8),('FONT',(0,2),(-1,2),'Helvetica-Bold',8),('BACKGROUND',(0,2),(-1,2),colors.HexColor('#E8F7FD')),('SPAN',(0,-1),(0,-1)),('SPAN',(1,-1),(1,-1)),('SPAN',(2,-1),(-1,-1)),('BACKGROUND',(0,-1),(-1,-1),soft),('FONT',(0,-1),(-1,-1),'Helvetica',6.5),('GRID',(0,1),(-1,-2),.3,colors.HexColor('#DCE4EA')),('VALIGN',(0,0),(-1,-1),'MIDDLE'),('LEFTPADDING',(0,0),(-1,-1),3*mm)]));story+=[KeepTogether([t,Spacer(1,4*mm)])]
story+=[Paragraph('METHODOLOGICAL AND SECURITY NOTE',styles['SectionKCS']),Paragraph('Counts shown in the final report are exact database totals, not survey estimates. Vote share uses valid votes for each office. The margin compares the two highest totals. HHI is the sum of squared vote shares and its reciprocal is the effective number of candidates. Ties are declared and never resolved automatically. The QR code links to the public verification record; the SHA-256 fingerprint detects any change to the certified report. These integrity markers complement, but do not claim to replace, a qualified electronic signature.',styles['BodyKCS']),Spacer(1,3*mm),Paragraph('SPECIMEN ONLY - Candidate names and values on this page are fictional and must not be interpreted as election results.',styles['CenterSmall'])]
doc.build(story,onFirstPage=decorate,onLaterPages=decorate)
print(OUT)
